name: Snyk example
on: push
jobs:
  snyk-go:
    uses: pratheesh-s1/github-actions/.github/workflows/snyk-go.yaml@main
    with:
      snyk-version: latest
      go-version: "1.22"
      severity-threshold: high