name: Snyk example
on: push
jobs:
  snyk-go:
    uses: pratheesh-s1/github-actions/.github/workflows/snyk-go.yaml@main
    with:
      runner-type: ubuntu-latest
      snyk-version: v1.1301.2
      go-version: "1.22"
      severity-threshold: high